<?php
include('/Users/macbook/Desktop/valet/clientChat/fns/minify/src/Minify.php');
include('/Users/macbook/Desktop/valet/clientChat/fns/minify/src/ConverterInterface.php');
include('/Users/macbook/Desktop/valet/clientChat/fns/minify/src/Converter.php');
include('/Users/macbook/Desktop/valet/clientChat/fns/minify/src/NoConverter.php');
include('/Users/macbook/Desktop/valet/clientChat/fns/minify/src/CSS.php');
include('/Users/macbook/Desktop/valet/clientChat/fns/minify/src/JS.php');
include('/Users/macbook/Desktop/valet/clientChat/fns/minify/src/Exception.php');
include('/Users/macbook/Desktop/valet/clientChat/fns/minify/src/Exceptions/BasicException.php');
include('/Users/macbook/Desktop/valet/clientChat/fns/minify/src/Exceptions/FileImportException.php');
include('/Users/macbook/Desktop/valet/clientChat/fns/minify/src/Exceptions/IOException.php');