<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit645977e3fe3fe11781720b5f9d994184
{
    public static $prefixesPsr0 = array (
        'F' => 
        array (
            'FtpClient' => 
            array (
                0 => __DIR__ . '/..' . '/nicolab/php-ftp-client/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit645977e3fe3fe11781720b5f9d994184::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit645977e3fe3fe11781720b5f9d994184::$classMap;

        }, null, ClassLoader::class);
    }
}
