<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5bee3e7426b37427dc3a5c78fb4e5592
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5bee3e7426b37427dc3a5c78fb4e5592::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5bee3e7426b37427dc3a5c78fb4e5592::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit5bee3e7426b37427dc3a5c78fb4e5592::$classMap;

        }, null, ClassLoader::class);
    }
}
